name: Git Actions

#on: [push]
on:
  push:
    branches:
      - master
      - 'feature/*' # matches feature/featureA or feature/B
      - 'feature/**' # match feature/demo/change

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: prathap
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time}}"
